import ReactQuery from '@/providers/ReactQuery';
import Theme from '@/providers/Theme';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQuery>
          <Theme>{children}</Theme>
        </ReactQuery>
      </body>
    </html>
  );
}
